# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  partner_connect_trial:
    # Applies to all files under models folder
    +materialized: view
    src:
      +materialized: ephemeral    
    dim:
      +materialized: view    
    fct:
      +materialized: table  